Introducing four new proposals to the repo: 5.9, 5.10, 5.11, 5.12
ensdomains/docs pull request #267
Opened 2024-07-22 19:40 UTC by estmcmxci

Introducing four new proposals to the repo: 5.9, 5.10, 5.11, 5.12

Issue #266 

https://github.com/ensdomains/docs/issues/266

2024-08-09 21:57 UTC, gskril requested changes
Thanks for contributing!

Looks like there are some mismatches between this PR and the live proposals. Also, please add these new links to the sidebar [here](https://github.com/estmcmxci/docs/blob/00518274958cdcc3fcbfd5df22aaa3a09d6668c7/app/local/config/navigation/protocol.ts#L416) so they show up on https://docs.ens.domains/dao

2024-08-09 21:57 UTC, gskril commented on docs/dao/proposals/5.10.mdx
This file is named `5.10` but the heading `[5.9] [Social] Funding Request: ENS Meta-Governance Working Group Term 5 (Q1/Q2)` indicates that something is mismatched

2024-08-09 21:57 UTC, gskril commented on docs/dao/proposals/5.9.mdx
Seems like this should be `5.9.1` unless I'm missing something https://snapshot.org/#/ens.eth/proposal/0x66d355555c24ed0d2fed0aee89e4fe009e2925c84144c4edc707d33e7c19e554

2024-08-09 21:57 UTC, gskril commented on docs/dao/proposals/5.12.mdx
Can we add the proposal's title as a heading like the others?

2024-08-14 18:31 UTC, estmcmxci commented
> Thanks for contributing!
> 
> Looks like there are some mismatches between this PR and the live proposals. Also, please add these new links to the sidebar [here](https://github.com/estmcmxci/docs/blob/00518274958cdcc3fcbfd5df22aaa3a09d6668c7/app/local/config/navigation/protocol.ts#L416) so they show up on https://docs.ens.domains/dao

All done, committing and pushing now.

2024-08-19 15:40 UTC, gskril requested changes
The metadata wasn't updated for EP 5.12. Otherwise looking good!

2024-08-19 15:40 UTC, gskril commented on docs/dao/proposals/5.12.mdx
> +    description: 'This proposal funds the Meta-Governance Working Group with 374k USDC and 150k ENS to support DAO-wide operations, including Working Groups, treasury management, and governance initi
```suggestion
    description: 'This proposal aims to roll out an updated version of the Zodiac Roles Modifier module.',
```

2024-08-19 15:40 UTC, gskril commented on docs/dao/proposals/5.12.mdx
> +        tally: '76312276134880424811339391717815330375652916610982980144903695563372140531115',
```suggestion
        tally: '107992041043258996427224563090014372885335179099580585497266204203463156791290',
```

2024-08-20 00:12 UTC, gskril approved these changes

2024-08-27 12:46 UTC, merged