Address ETHGlobal SF feedback
ensdomains/docs pull request #336
Opened 2024-10-21 21:23 UTC by gskril

2024-10-29 12:16 UTC, lucemans requested changes

2024-10-29 12:16 UTC, lucemans commented on app/public/_redirects
> +/web/namehash /resolution/names#namehash
```suggestion
/web/namehash /resolution/names#namehash

```

2024-10-29 22:02 UTC, Nmhth17 commented on app/public/edgerc.json
> +                "pattern": "^/web/namehash$",
Nmhpjd17.eth

2024-11-15 07:44 UTC, lucemans approved these changes
LGTM

2024-11-15 07:44 UTC, lucemans commented on docs/resolvers/ccip-read.mdx
> +The Unruggable Gateway is a gateway that allows you to load data from specific Layer 2's whose proofs are verifyable on L1.
```suggestion
The Unruggable Gateway is a gateway that allows you to load data from specific Layer 2's whose proofs are verifyable on L1.
```

2024-11-15 07:44 UTC, merged