Added web3j code samples
ensdomains/docs pull request #364
Opened 2024-11-28 07:57 UTC by NickSneo

This PR adds code samples for Web3j library - https://github.com/hyperledger-web3j/web3j

2025-01-10 04:55 UTC, gskril requested changes
thanks for contributing and sorry for the review delay! just have one comment about labelhash

2025-01-10 04:55 UTC, gskril commented on docs/resolution/names.mdx
> +byte[] labelHash = NameHash.nameHashAsBytes('label');
Labelhash is the keccak256 hash of the label (e.g. "nick" in the name "nick.eth"), which is different than applying `NameHash.nameHashAsBytes()` on the label.

Web3j likely doesn't have a helper function specific to labelhash, but it may have a keccak256 function which can be used in this example.

2025-01-10 07:38 UTC, NickSneo commented on docs/resolution/names.mdx
> +byte[] labelHash = NameHash.nameHashAsBytes('label');
So `NameHash.nameHash` Function can be used for both full Name like `nick.eth` and just label like 'nick`
It will give the correct result, thats why there is no ultitly function just for labels as user can use current `NameHash.nameHash` fucntion on label to get the labelHash.

This fuctions returns (Hash.sha3(result)) which is keccak256
Hope it makes sense, let me know if there is still any confusion

2025-01-10 16:37 UTC, gskril commented on docs/resolution/names.mdx
> +byte[] labelHash = NameHash.nameHashAsBytes('label');
Hmmm I'm running a test script locally and `NameHash.nameHashAsBytes('label')` does not return the expected label hash. The expected value for `label` would be `0x1b036544434cea9770a413fd03e0fb240e1ccbd10a452f7dba85c8eca9ca3eda`

I don't know Java well, but futzing around it looks like the code example will have to be a bit lower level like this:

```
public static String labelHash(String name) {
      // Get the label of the name (the part before the earliest '.')
      String[] parts = name.split("\\.");
      String label = parts[0];

      // Keccak256 hash the label and convert to hex string
      byte[] labelHash = Hash.sha3(label.getBytes(StandardCharsets.UTF_8));
      String labelHashString = Numeric.toHexString(labelHash);
      return labelHashString;
    }
```

2025-01-10 16:42 UTC, gskril requested changes
Sorry I missed this the first time — would be great if you can include the relevant imports for each example so they're truly copy/paste snippets!

2025-01-10 16:42 UTC, gskril commented on docs/resolution/names.mdx
> +String nameHashString = Numeric.toHexString(nameHash)
Looks like web3j also exposes [`NameHash.nameHash`](https://github.com/hyperledger-web3j/web3j/blob/main/core/src/main/java/org/web3j/ens/NameHash.java#L37-L40) which returns a hex string directly, so no need to first get the bytes and convert it yourself

2025-01-16 07:24 UTC, NickSneo commented on docs/resolution/names.mdx
> +byte[] labelHash = NameHash.nameHashAsBytes('label');
@gskril Thanks for pointing out this. I was able to reproduce it, and created a PR for labelHash fucntion - https://github.com/hyperledger-web3j/web3j/pull/2140

We will soon release new Web3j with this fix. Thanks

2025-04-21 21:27 UTC, gskril commented
The docs have been refactored quite a bit since this PR was opened, so I'm closing it for simplicity. It looks like the fix to the upstream library was merged, so I'd be happy to review a new PR if you get around to it!

2025-04-21 21:27 UTC, closed without merging